### ISSUE TITLE
EasyData support for Master Detail CRUD

### ISSUE THREAD

**Issue by weedkiller** [KorzhCom/EasyData#10]
Hello, I was looking at your demo, majority of the applications we have use Master-Details CRUD with auditing/Tenant ID, there is a free plugin by [zzz for auto-autdits here](https://github.com/zzzprojects/EntityFramework-Plus)

- [ ] If you could add the master detail it would be very helpful.
- [ ] Selected row on the master while editing master or detail page show be clear
- [ ] Also, how can we merge this with the save query choice to user after setting

**Comment by korzh** [comment]
Hello,

1. We plan to add support for master-detail CRUD in one of the next updates. 
2. 3. I'm not sure I quite understood these 2 requests. Could you elaborate a little more? Especially in #3, what did you mean by "save query choice"?

**Comment by weedkiller** [comment]
Can you put all your components in one demo with ASP core, its better for you too, since the developer will see other samples too if they don't know they are there.
I was confused between your query and data sorry, I thought I could use any table and save those queries

**Comment by korzh** [comment]
Did you mean both EasyData and EasyQuery? Yes, we plan to do that in the future. As for now, EasyData is for CRUD operations mainly and EasyQuery is more for data search, filtering, and reporting.  

We've made the first step to that goal with version 7.0 of EasyQuery (will be released in a few days). Now it's based on EasyData.Core package to avoid duplication of functionality in both these libraries. 
However, they are still separate libraries. EasyData is an open-source one, while EasyQuery is commercial.

Anyway, I'm still confused with your second request in this issue.  What did you mean by "selected row ... should be clear"? The selected row can always be distinguished from the others by its background color and (sometimes) bolder font. What else can we do to make more clear which row is selected?
