### ISSUE TITLE
Search does not work on some tables with numeric fields

### ISSUE THREAD

**Issue by korzh** [KorzhCom/EasyData#105]
The problem is reproducible on the "Order Details" table used in our samples.

If we type a numeric value (e.g. 100) in the search box and press Enter (or click on the Search button) we will not get any changes in the view. The `.../fetch` request returns status code 400 with a description of the exception that occurred on the server-side.

**Comment by antifree** [comment]
@korzh  Could not reproduce problem in playground
![image](https://user-images.githubusercontent.com/28184848/150641821-4dc5a85a-69d3-4ebc-8407-44030c87df2a.png)

**Comment by korzh** [comment]
True. I can't reproduce this problem either. 

There is another little issue with this functionality: we don't search on float/currency fields while it's not something that is difficult to implement. However, that will be a totally new issue.

This one is closed for now.
