### ISSUE TITLE
When editing, the enum is always the default

### ISSUE THREAD

**Issue by Alerinos** [KorzhCom/EasyData#107]
When editing, the enum is always the default, it doesn't get the value from the database

![image](https://user-images.githubusercontent.com/42449535/149861954-362c4edb-d79f-4b19-8e9d-51e4cb1008b2.png)
![image](https://user-images.githubusercontent.com/42449535/149861998-9a938672-58d1-42fb-a102-1846cf98210d.png)

It should be the same as in the database.

Model:
```cs
public class Game
{
    [Key]
    public Guid Id { get; set; }
    public string Name { get; set; } = string.Empty;                
    public StatusType Status { get; set; }                          

    public enum StatusType
    {
        Verification,           
        Show,                   
        Hide,                   
        Recommended            
    }
}
```

**Comment by antifree** [comment]
Fixed in 1.4.2
