### ISSUE TITLE
Problem with easydata 1.3.0 JS

### ISSUE THREAD

**Issue by sanket-pattekar** [KorzhCom/EasyData#109]
Hi

I have upgraded to nuget package 1.4.1 and also refernced to 1.3.0 JS file. With this upgrade, the entity listing page works, but the entity detail page fails. If I revert the JS file, then the pages load properly with the latest version.

So there is some issue with the 1.3.0 JS file.

Sanket

**Comment by korzh** [comment]
Hello,

Yes, we have changed the API endpoints a little in version 1.4.0. So, if you use 1.4.0+ (I mean 1.4.0 or higher) version of the packages you also should use version 1.4.0+ of scripts and vice versa
