### ISSUE TITLE
[Idea] Additional information about the table

### ISSUE THREAD

**Issue by Alerinos** [KorzhCom/EasyData#112]
I got the idea that it would be nice to add information about it on the home page and in the table details. I mean, how many records are there, how many data takes (kb/mb), once I saw a ready-made function that returns all such information. A simple thing and I think it will help and be useful.

What do you think about this?

**Comment by antifree** [comment]
Hello, thank you for your proposal. 
Here are my thoughts about it:

- The home page is just a selector for entities with its description. 
- The number of records is available in the grid.
- Size of the data table is not information that is needed for all users of EasyData

Moreover, to render the home page we do not make requests to a database at all, all the information is taken from DbContext metadata, what you propose cannot be done without additional requests to the database

@korzh, What do you think?

**Comment by korzh** [comment]
Totally agree with @antifree 

It would be nice to have this info in some cases but this feature is definitely not needed for everyone and requires a lot of additional requests to DB (1 extra request per each entity at least). 

I think what we can do, is to provide an easy way for adding this info (or any extra data) into existing list items (on the Root view) and, maybe, a bunch of functions (both on the frontend part and in the API) that will help to collects this information for those who need it.

Obviously, it's not a priority functionality.
