### ISSUE TITLE
Feature: Add security/role/claim for what user can do 

### ISSUE THREAD

**Issue by weedkiller** [KorzhCom/EasyData#12]
This is very nice now I understand, the 5.0 Sample builds fine with the latest, 

Must - Master Details is a Must.
The columns, grid should be responsive (fit page/container)
Option to use DTO's
Option to use AutoMapper ORM Mapper
Must - Security is very important, on what role the user can do, for e.g it should create a new view with the list of tables and which ones are, options/checkboxes on C R U D permissions and Map it or create a role.
Change the Icon for the navigation properties, or let user configure, if the page is small height its hidden
Allow to select which items are viewable.
Option for Audit Table, which user performed which action/Update on what date.
Notification to user when data has been saved
Manager/Data Handler would be nice if it was fluent.
Option for lazy loading and searching the table for records.

**Comment by weedkiller** [comment]
What is `EasyData.db-SHM` &  `EasyData.db-SHM` my work sent me an email that my laptop was infected!

**Comment by korzh** [comment]
Hello,

Please open an issue for each particular request separately. Like, "master-details" - one issue, "responsive grid" - another one, etc. In this case, we will be able to close it one by one and you will be notified when a particular feature is implemented.

**Comment by korzh** [comment]
And what about that `EasyData.db-SHM` file? As far as I can see we don't have any file with this name in our repository. 
Possibly it's something that is generated automatically by Visual Studio when you install a NuGet package?

**Comment by antifree** [comment]
Hello, 

`EasyData.db` is an sqlite database, which samples use. You can find it in [appsettings.json](https://github.com/KorzhCom/EasyData/blob/e75ab13b7f6e5b283f468fa027ae9e3ccd3bbabd/samples/EasyDataBasicDemo.Net5/appsettings.json#L12)

**Comment by weedkiller** [comment]
ok. I will close it, do you know when Master - Details will be available. 
I saw I was using EF reverse poco maybe thats generating it will check.
