### ISSUE TITLE
Displaying the name in relationships

### ISSUE THREAD

**Issue by Alerinos** [KorzhCom/EasyData#124]
How to make the displayed relation show a specific column, in this case name instead of ID?
Somewhere I saw that it can be done in the endpoint but unfortunately I can't find it. Unfortunately, the ID relations make it difficult to search and navigate the database. On the gif in readme you can see that the relation is working.

Models:
```cs
public class Details
{
    public int Id { get; set; }
    public User User { get; set; } = null!;
    public Guid UserId { get; set; }
    public string? FirstName { get; set; }                      // Imię
    public string? LastName { get; set; }                       // Nazwisko
    public string? Description { get; set; }                    // Złota myśl użytkownika, jego opis etc
    public string? Avatar { get; set; }                         // Zdjęcie profilowe
    public SexType Sex { get; set; } = SexType.None;            // Płeć

    public enum SexType
    {
        None,
        Man,
        Woman,
    }
}
```

```
public class User
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(16, MinimumLength = 4), Required]
    public string Name { get; set; } = String.Empty;                                     // User name
}
```
![image](https://user-images.githubusercontent.com/42449535/163265767-c3f329c3-164d-485b-b280-55e632f49fb9.png)
![image](https://user-images.githubusercontent.com/42449535/163265813-0de6086d-59d2-446a-aac9-c06bf3ce5ee5.png)
![image](https://user-images.githubusercontent.com/42449535/163266369-39b42ccc-b52a-4453-a055-f3792bf29dd3.png)

**Comment by antifree** [comment]
Currently, this feature is not supported. We will close this feature due to duplication of #108

**Comment by howest-alexander** [comment]
> Currently, this feature is not supported. We will close this feature due to duplication of #108

Is this feature on the roadmap? I think this feature is really necessary to have an user friendly experience and to let non technical people work with the forms.

It should also be possible to choose which field to show in the navigation property on the form.

Can someone give some tips on how to create this feature in the project? 
Was there already an analysis created for this feature?

**Comment by korzh** [comment]
Yes, it's in the roadmap but I can't give you any timeframe for now
