### ISSUE TITLE
Support description

### ISSUE THREAD

**Issue by Alerinos** [KorzhCom/EasyData#125]
https://docs.microsoft.com/pl-pl/dotnet/api/system.componentmodel.descriptionattribute?view=net-6.0
You can enter support description. Information from the Attribute can be displayed in the following form:
![image](https://user-images.githubusercontent.com/42449535/163714495-468d9fff-bc35-4e78-bbea-4a203161e81b.png)

**Comment by Alerinos** [comment]
![image](https://user-images.githubusercontent.com/42449535/163714614-6c92b993-d5a4-491e-8497-dbb1c7f23280.png)
You can also enter a description here, it will facilitate the database management by people who did not create it. Such a mini documentation

**Comment by antifree** [comment]
Hello.
We support description via out MetaEntityAttribute and MetaEntityAttrAttribute
```c#
[MetaEntity(Description="The orders")]
class Order
{
      [MetaEntityAttr(Description="The order date")]
      public DateTime OrderDate {get; set;}
}
```
Or via our fluent API
```c#
app.UseEndpoints(endpoints => {
    endpoints.MapEasyData(options => {
        options.UseDbContext<ApplicationDbContext>(opts => {
            opts.CustomizeModel(model => {
                model.Entity<Order>()
                    .SetDescription("The orders")
                    .Attribute(o => o.OrderDate)
                           .SetDescrition("The order date");
            });
        });
    });
});
```

Ant the description will be displayed exactly as you proposed

**Comment by antifree** [comment]
We are open to contribution if you want to add support of `DisplayAttribute` as well :)

**Comment by Alerinos** [comment]
@antifree Thanks for writing back, in theory you can use Display, there is name, description and whatever you need.

https://github.com/KorzhCom/EasyData/blob/6a8ecec02923ee10cb4026c1432dee62c018a906/easydata.net/src/EasyData.EntityFrameworkCore.Relational/MetaDataLoader/DbContextMetaDataLoader.cs#L395-L466

```cs
if (propInfo.GetCustomAttribute(typeof(DisplayAttribute)) is DisplayAttribute displayAttr) {
                    entityAttr.Caption = displayAttr.Name;
                    entityAttr.Description = displayAttr.Description;
}
```
If I understand the assumption of your code correctly, just do something like this and it should work. I understand well? 😄

**Comment by antifree** [comment]
Yes. You are right, thank you. I'll add with next release

**Comment by antifree** [comment]
Add 3b49c869d785b4c2422f6ffc5c1e6bea2a31788e. Will release it tomorrow

**Comment by antifree** [comment]
Done in version 1.4.4

**Comment by Alerinos** [comment]
![image](https://user-images.githubusercontent.com/42449535/164443352-8a0ef26e-f0a3-451c-b3c4-fd286e72710c.png)
Works great, thanks!
In theory, you can still make a description here.

**Comment by antifree** [comment]
We will consider this, thank you!
