### ISSUE TITLE
Edit/Delete not showing the correct entry when it's filtered

### ISSUE THREAD

**Issue by weber2up** [KorzhCom/EasyData#127]
As title. 

To reproduce:
1. Filter the table using Search
2. Click on Edit or Delete on one of the entries.
3. The dialogue box showing different entry

**Comment by korzh** [comment]
Fixed with commit [bed93bb](https://github.com/KorzhCom/EasyData/commit/bed93bb60e6483c827622aee6425408fa83f9416)

It works for now but it's better to rewrite the way it refreshes the grid after a record deletion.
