### ISSUE TITLE
The HTML code displayed in the column

### ISSUE THREAD

**Issue by Alerinos** [KorzhCom/EasyData#133]
![image](https://user-images.githubusercontent.com/42449535/168167740-f7db5433-589c-4f24-885e-a6118840067c.png)
![image](https://user-images.githubusercontent.com/42449535/168167767-fc9cfdf5-97c2-463a-9975-22fb0ef699dc.png)

I believe it should not display html code formatting. It may also have a security impact, if <script> is added it will be executed.

**Comment by antifree** [comment]
Good point, thank you. It is fixed and will be published with version 1.4.5 today
