### ISSUE TITLE
Add error throwing for unsupported field types

### ISSUE THREAD

**Issue by rodion-m** [KorzhCom/EasyData#135]
Please add error throwing for unsupported field types. For example if we forget to skip field that has type `Instant` from NodaTime library:
```csharp
    public class User
    {
        public Guid Id { get; set; }
        public Instant CreatedAt { get; set; } //<-- Bugged field, I forgot to add [MetaEntityAttr(Enabled = false)] here.
    }
```
Then easydata shows only white table without any chance to get known what's wrong:
![image](https://user-images.githubusercontent.com/36400912/169164845-2122e7ed-7ee9-4aa1-95f6-e42de18e8852.png)
Also easydata wrote an error to console:
```
easydata.min.js:2 
       TypeError: Cannot read properties of undefined (reading 'max')
    at s (easydata.min.js:2:128045)
    at e.resizeColumns (easydata.min.js:2:128433)
    at easydata.min.js:2:113992
    at A (easydata.min.js:2:95263)
    at k (easydata.min.js:2:95156)
    at MutationObserver.g (easydata.min.js:2:93153)
```
I've spent 2 hours to find it out, so please add an exception throwing for this case for example.

**Comment by korzh** [comment]
I guess it's better to just ignore such properties.

**Comment by rodion-m** [comment]
Does EasyData support logging, right? So, you can just write warnings in the log about unsupported types and on EasyData initialization and then ignore them.

**Comment by korzh** [comment]
OK.

Can you share an exmple of the project with NodeTime and EasyData used together?
We would like to reproduce the situation like in your issue.

**Comment by antifree** [comment]
@korzh  doest it related to this issue?

**Comment by korzh** [comment]
> @korzh doest it related to this issue?

What do you mean?

**Comment by antifree** [comment]
@korzh my fault, missed in the description NodeTime library mentioning sorry

**Comment by korzh** [comment]
We've partially fixed this issue (unsupported types are just ignored now) and moved the second task (a warning about an unsupported type) to the issue #136
