### ISSUE TITLE
Long col names over run - need to over-ride col names

### ISSUE THREAD

**Issue by weedkiller** [KorzhCom/EasyData#14]
It looks like its taking the col names from the table. Is it possible to over ride these col & table names, for e.g. they maybe long or we may have 

Site1_Table, Site1_Tableb and dont want to show those table/col names

**Comment by antifree** [comment]
Yes, it is possible via `MetaEntity` and `MetaEntityAttr` attributes.

For example:
```c#
[MetaEntity(DisplayName="Order", DisplayNamePlural="Orders")]
public class Order {

      [MetaEntityAttr(DisplayName="Ordered")]
      public DateTime OrderedDate {get; set;}
}
```

**Comment by weedkiller** [comment]
thanks
