### ISSUE TITLE
A possibility to set up a "one entity" view

### ISSUE THREAD

**Issue by korzh** [KorzhCom/EasyData#15]
Currently, we can set up a "catch-all" page that will serve CRUD for all entities in our DB (or at least the ones we make as available in our DbContext).

However, it's often necessary to quickly set up a CRUD page for one entity (e.g. only "Customer") on a separate page that does not fits to `/easydata/{entity}` pattern. 

It would be possible if our EasyDataViewDispatched could accept a `rootEntity` option, so its behavior would be the same as we opened `/easydata/{rootEntity}` page. 

An example of the EasyData initialization code in such a case:

```
window.addEventListener('load', () => {
    new EasyDataViewDispatcher({
        rootEntity: 'Customer'
    }).run()
});
```

**Comment by antifree** [comment]
In this case, all entities still will be editable via REST API (middleware). If it is OK, we can close this issue
