### ISSUE TITLE
Support for many filters in GetEntities request 

### ISSUE THREAD

**Issue by korzh** [KorzhCom/EasyData#16]
Currently, we can set only one filter with any `GetEntities` request (a kind of `contains` for string and, in some cases, numeric values). 

However, it could be very useful to have a possibility to define several different filters when we retrieve data from a database. 

For example, users may want to work only with the data that belongs to a particular period of time (e.g. "this year") or fits some other common criteria (e.g. `department = 'sales'`).

So, to allow to implement the behavior mentioned above we need to make the following changes:

1. GetEntitites request must accept `filter: [ {...}. {...}, ...]` parameter (an array of objects) instead of `filter: 'text'` accepted now.
2. Each object in that list will define one filter. The object must contain one required property `class` that will define the class (type) of the filter. Other properties will define different filter parameters.
3. We will have a number of default filter classes.  For example, there will be the `__substring` class (will act the same way as the current `filter` parameter) or `__datePeriod` class that will allow filtering by a period of time. The class name for the default filters will be prefixed with `__`. 
4. EasyData users (I mean developers here) will be able to define any custom filters via a kind of registration mechanism (this is a matter of a separate issue) both on the client-side and server-side.

**Comment by antifree** [comment]
Implemented server-side filter registration 45037f27bc2a7897631d07d6d087b5c7718a596e
