### ISSUE TITLE
Некорректное сопоставление записей в результирующей выборке поиска

### ISSUE THREAD

**Issue by Juggernauff** [KorzhCom/EasyData#172]
Как воспроизвести ошибку:
1. Найдите в поиске любую запись.
2. Попробуйте её удалить/изменить.

С вероятностью 99.9% запись, которую вы хотите удалить/изменить определится неправильно (может определиться "правильно", если номер строки совпадет с её id).

Если же изменять/удалять запись не из результирующей выборки поиска, а из первоначальной результирующей выборки - всё будет работать корректно.

**Comment by korzh** [comment]
Доволі дивно адже механізм видалення вибирає запис не за його порядковим номером в таблиці, а за первинним ключем (primary key) або ключами.

Спробуємо повторити та виправити проблему але, нажаль, процес не буде швидким, адже основний час зараз займає робота по знищенню відомого терористичного угрупування, що вдерлося в мою країну.

З повагою, Сергій Корж, ст. лейтенант ЗСУ.

**Comment by korzh** [comment]
Спробував повторити проблему з останньою версією 1.4.18 - не виходить. Все видаляється корректно.
Можете розписати як повторити проблему на одному з sample проєктів, що додані до репозиторію?

Єдине що знайши, список записів чомусь не оновлюється автоматично після видалення (тобто ми продовжуємо бачити видалений запис). Але якщо зробити оновлення вручну - то все ОК.

**Comment by Juggernauff** [comment]
Велике спасибі за відповідь.
Постараюся дати свою зворотний зв'язок на більш близькому вам мовою.

Для достовірності експерименту я видалив локальне сховище і використав `git clone` заново. За приклад беру проект ' Easy Data Basic Demo.MVC.Net6`.

Мені варто було раніше подбати про це і прикласти скріни, але я зроблю це зараз.

Мої кроки:
1. Перейшов на EasyData;
2. Перейшов в Categories;
3. Знайшов в пошуку запис під id: 8;
4. Спробував її видалити (видно, що пропонує видалити запис під id: 1);
5. Я отримую помилку;
6. Намагаюся змінити;
7. Перевіряти (змінено запис під id: 1).

Я буду радий, якщо допоможу покращити ваш проект.

![step_1](https://github.com/KorzhCom/EasyData/assets/66491707/991b9828-32b8-459d-9dbc-32b46a79b6c8)
![step_2](https://github.com/KorzhCom/EasyData/assets/66491707/712fd40b-a61a-455a-97d8-eb8c6d03fab1)
![step_3](https://github.com/KorzhCom/EasyData/assets/66491707/e9b24629-38d7-4d7e-9d5a-10cf82f9e90d)
![step_4](https://github.com/KorzhCom/EasyData/assets/66491707/0a123799-11e4-4f6c-a454-e2270b3d3ce4)
![step_5](https://github.com/KorzhCom/EasyData/assets/66491707/2791f7d0-b163-41f3-be9f-8b59b3e78334)
![step_6](https://github.com/KorzhCom/EasyData/assets/66491707/aa380153-c653-4332-8a82-e515d5ccaccf)
![step_7](https://github.com/KorzhCom/EasyData/assets/66491707/3dabb3cf-aa7c-42c9-91ab-c8c322dce60d)

**Comment by korzh** [comment]
Власне, то я намагався написати найбільш близькою до вас мовою. Бо репозиторій загалом та більшість з issues ведуться англійською.

Nevertheless.  
Проблема була в самому демо проєкті. Ми там просто забули оновити версію EasyData скрипта до останньої (1.4.18). 
Я просто тестував цю проблему на інших проєктах і там вона, очевидно, не проявлялась.
Після оновлення скрипта все працює нормально. Я вже залив останні зміни в репозиторій. Думаю можемо закривати цей issue.
