### ISSUE TITLE
Typescript error with i18n.d.ts

### ISSUE THREAD

**Issue by dmoonfire** [KorzhCom/EasyData#21]
I'm trying to use the 1.2.1 version of @easydata/core and I'm getting this error in Typescript version 3.9 and 4.1.

```
C:\Source\node_modules\@easydata\core\dist\lib\i18n\i18n.d.ts(21,9): error TS2411: Build:Property 'ButtonOK' of type 'string | undefined' is not assignable to string index type 'string | TextResources'.
C:\Source\node_modules\@easydata\core\dist\lib\i18n\i18n.d.ts(22,9): error TS2411: Build:Property 'ButtonCancel' of type 'string | undefined' is not assignable to string index type 'string | TextResources'.
```

From what I understand, your index lookup doesn't match the defined variables in that file. So either `ButtonOK` and `ButtonCancel` should be `string | TextResources` or `[propName: string]` should just be `string`. Regardless, it is also complaining if you don't have a `| undefined` in the `[propName]` property.

```
    interface TextResources {
        ButtonOK?: string;
        ButtonCancel?: string;
        [propName: string]: string | TextResources;
    }
```

Not sure if that is the correct fix or not, the compiler just complains less.

**Comment by antifree** [comment]
Hello,

thank you for letting us know about this issue. We will investigate it. 

For now, as a workaround, you can configure tsconfing.json to ignore errors in libraries:
```
{
    "compilerOptions": {
        "skipLibCheck": true,
        ...
    },
    ...
}
```

**Comment by antifree** [comment]
Hello,

we have published version 1.2.2. It must fix your problem

**Comment by dmoonfire** [comment]
Thank you, that solved my problem.

**Comment by antifree** [comment]
Nice to hear that!
