### ISSUE TITLE
Off-by-one bug in easyDataTable

### ISSUE THREAD

**Issue by Kot-Zakhar** [KorzhCom/EasyData#26]
Hello. I've found a bug in your code.
It shows up when I try to load data using context.FetchData() passing to chunk.pageSize the same value as table.chunkSize has.
I expect it to load and return a full single chunk, but it loads two chunks due to this.

I guess, the right code will look like this:
``` typescript
let endIndex = fromIndex + count - 1;
```

https://github.com/KorzhCom/EasyData/blob/74ff10a87701f3866307d5cff12eb765a6924d3b/easydata.js/packs/core/src/data/easy_data_table.ts#L94

**Comment by korzh** [comment]
Agree. Will be fixed in the next update.

**Comment by antifree** [comment]
Hello,

thank you for the report. We will investigate this situation.

**Comment by antifree** [comment]
Hello,

version 1.2.4 with fix has been published.
