### ISSUE TITLE
Doesn't wotk in API project. Got just white screen.

### ISSUE THREAD

**Issue by AlexandrSurkov** [KorzhCom/EasyData#3]
Hi. I tryed to run it, but got the clean white screen. Is there any way to debug it or any other way to find what I did wrong?

**Comment by korzh** [comment]
Could you please add the markup of the ".cshtml" file for your "catch-all" page? 

You can try to open Developer Tools in your browser on that page to see if there are any console errors or problems with API requests.

**Comment by AlexandrSurkov** [comment]
Hi. I took the page from the Readme.md:

@page "/easydata/{**entity}"
@{
    ViewData["Title"] = "EasyData";
}
<link rel="stylesheet" href="https://cdn.korzh.com/ed/1.1.1/easydata.min.css" />

<div id="EasyDataContainer"></div>

@section Scripts {
    <script src="https://cdn.korzh.com/ed/1.1.1/easydata.min.js" type="text/javascript"></script>
    <script>
        window.addEventListener('load', function () {
            new easydata.crud.EasyDataViewDispatcher().run()
        });
    </script>
}

Also, I use PostgreSQL, tut in shouldn't affect... 

After some time after loading there is an error: Unchecked runtime.lastError: The message port closed before a response was received.

I use Chrome.

![image](https://user-images.githubusercontent.com/17044185/100593857-fbf82d00-3309-11eb-9a22-3f0821bb03fa.png)

**Comment by korzh** [comment]
Hello,

1. First of all, I don't see the `link` element that loads the EasyData CSS on your page. It does not cause the error of course but it's required for proper rendering of all forms and dialogs.

2. Could you please share the Network tab as well? 

3. What is the configuration of EasyData middleware (`endpoints.MapEasyData(...)`) in your `Startup.Configure`?

**Comment by korzh** [comment]
One more question (we actually had to start with it): 

Have you tried to run the sample included in this repository?

**Comment by AlexandrSurkov** [comment]
> One more question (we actually had to start with it):
> 
> Have you tried to run the sample included in this repository?

No, I haven't

**Comment by AlexandrSurkov** [comment]
> Hello,
> 
> 1. First of all, I don't see the `link` element that loads the EasyData CSS on your page. It does not cause the error of course but it's required for proper rendering of all forms and dialogs.
> 2. Could you please share the Network tab as well?
> 3. What is the configuration of EasyData middleware (`endpoints.MapEasyData(...)`) in your `Startup.Configure`?

Link is exist:

![image](https://user-images.githubusercontent.com/17044185/100600879-f18e6100-3312-11eb-952a-30063887ed70.png)

Network tab is clean:

![image](https://user-images.githubusercontent.com/17044185/100601031-26021d00-3313-11eb-9070-484d91dd9b5f.png)


![image](https://user-images.githubusercontent.com/17044185/100601659-eb4cb480-3313-11eb-9cfd-ebb52e787f00.png)

**Comment by korzh** [comment]
1. Could you please try to run the sample? The database used there must be created automatically in your local SQL Server instance at first start. We just need to check if the problem is with your particular configuration or it's more general issue.

2. It seems the problem with that error message in the console ("Unchecked runtime.lastError:..") is [caused by some Chrome extension](https://stackoverflow.com/questions/54126343/how-to-fix-unchecked-runtime-lasterror-the-message-port-closed-before-a-respon)

3. Could you place some element on that page to check if it's rendered well. For example: `<h2>Here will be the CRUD</h2>`

4. By the way, there is no need to add Razor pages just to run the EasyData. You can use a "catch-all" MVC controller action (and the corresponding view) as well.

5. Following the previous point, I guess the Razor Pages functionality is a new thing for your project. Have you added the necessary services in `Startup.ConfigureServices`?
 
```
 .   .   .   .
services.AddRazorPages();
```

**Comment by AlexandrSurkov** [comment]
> * `<h2>Here will be the CRUD</h2>`
> *

1. The sample works fine.
2. I tried to use Microsoft EDGE, but the result is the same - white clean page
3. If I add <h2>Here will be the CRUD</h2> - I see it:
![image](https://user-images.githubusercontent.com/17044185/100641109-1bae4600-3348-11eb-8194-b4619ee48b9a.png)
4. I know. But I try to use Easy Data in the .Net Core 3.1 Web Api project - as a tool to work with database while testing the API.
5. Yes. my Startup.ConfigureServices contains services.AddRazorPages();

From my side - it seems that someting wring with js function. Because in sample project the page loading for some time, but in my project the page loads very fast - like the script finish it's work in the beginning...

**Comment by korzh** [comment]
I have an idea of why it might not work. Do you have a `_Layout.cshtml` file in `Pages/Shared` folder?

You need the one because otherwise, it will skip that `@section Scripts` piece. If you don't want to add a _Layout, you can simply move the content of the Scripts section out of `@section` block.

**Comment by AlexandrSurkov** [comment]
> I have an idea of why it might not work. Do you have a `_Layout.cshtml` file in `Pages/Shared` folder?
> 
> You need the one because otherwise, it will skip that `@section Scripts` piece. If you don't want to add a _Layout, you can simply move the content of the Scripts section out of `@section` block.

Thats it! Thank you very much. I moved the scrypt outside of the @section and everything now works well!
![image](https://user-images.githubusercontent.com/17044185/100649664-d2fc8a00-3353-11eb-8cdb-8d3ebeb72bf0.png)

I think it could be usefull if you put this info in the readme :)
