### ISSUE TITLE
http://<site_name>/<application_name> in IIS, EasyDataViewDispatcherOptions property 'endPoint' resolving not working properly

### ISSUE THREAD

**Issue by fara-ru251** [KorzhCom/EasyData#31]
Hello  EasyData contributors, your library is great, but I think there exist one bug with EasyDataViewDispatcher class resolving with routes.
Example: I have an application located in IIS like this: http://<site_name>/<application_name> 
and when I try to testing that all is working properly,  URL (http://<site_name>/api/easydata/models/__default) in DevTools giving the result of 404 (Not Found). So the problem is that, aforementioned URL must be http://<site_name>/**<application_name>**/api/easydata/models/__default instead of http://<site_name>/api/easydata/models/__default. I hope that I'm doing wrong, but my attempts to get around it were in vain. Thanks! Have a good day!

**Comment by antifree** [comment]
Hello,

You can try to change the endpoint on the client-side.

```html
 <script>
        window.addEventListener('load', function () {
            new easydata.crud.EasyDataViewDispatcher({
                 endpoint: '/<application_name>/api/easydata'
            }).run()
        });
    </script>
```

**Comment by fara-ru251** [comment]
I tried to do this, but it didn't help. I've tried any combination of tuning, in Startup.cs also.
My last tuning looks like this:
`<script>
        window.addEventListener('load', function () {
            new easydata.crud.EasyDataViewDispatcher({
                basePath: '<application_name>',
                endpoint: '/api/easydata'
            }).run()
        });
    </script>`
and Startup.cs
` endpoints.MapEasyData(options =>
                {
                    options.Endpoint = "/<application_name>/api/easydata";
                    options.UseDbContext<AnticorContext>();
                });`

**Comment by antifree** [comment]
You should not set `basePath` (it is used to change all-catch page URL to render switching between entities) or change the server-side endpoint in this case. Have you tried just to set the endpoint with the value, I proposed?

**Comment by fara-ru251** [comment]
Magic happens, thanks a lot for your proposition! My mistake was that I tune both side (client & server). Now it works great! Sorry for the trouble and thank you!

**Comment by antifree** [comment]
Happy to hear it 😊
