### ISSUE TITLE
Simple example for MVC

### ISSUE THREAD

**Issue by romanov** [KorzhCom/EasyData#32]
Is it possible to use the library without Razor Pages?

How to setup the basic controller for it?

`endpoints.MapControllerRoute("easydata", "/easydata/{**entity}", defaults: new { controller = "easydata" });` - no luck

Thank you.

**Comment by antifree** [comment]
Hello,

Thank you for your request. We will add an example

**Comment by antifree** [comment]
We have added an MVC sample. Here is an implementation of the catch-all [controller](https://github.com/KorzhCom/EasyData/blob/master/samples/EasyDataBasicDemo.MVC.Net5/Controllers/EasyDataController.cs)

**Comment by antifree** [comment]
Closed due to inactivity
