### ISSUE TITLE
Default Entity fields sorting

### ISSUE THREAD

**Issue by azakharko** [KorzhCom/EasyData#38]
Let's not sort Entity Fields by default - consider to configure this as an option.
It's not always the best choice if API decide whenever your fields should be sorted or not - but it's still valuable to control it explicitly

**Comment by azakharko** [comment]
@korzh yes, this would be preferable (and predictable) behavior. 
It's still nice-to-have an ability to define sorting algorithm for fields generation - I believe this could be implemented in `EasyDataOptions`

**Comment by antifree** [comment]
Done in version 1.3.0.

Example of usage:
```c#
endpoints.MapEasyData((options) => {
      options.UseDbContext<AppDbContext>(opts => opts.KeepDbSetDeclarationOrder = true);
});
```

**Comment by azakharko** [comment]
Yay! Well done! Thanks!
