### ISSUE TITLE
Custom EasyData page URL

### ISSUE THREAD

**Issue by ilchenkob** [KorzhCom/EasyData#4]
It's not an issue but question.
How can I use base page URL other than "/easydata/{url?}" for my EasyData page?
Right now I have this as a first line on my page:
```HTML
@page "/easydata/{url?}"
```
It works fine but when I change it to something like `@page "/data/{url?}"` I have blank page and this in browser's console:

![image](https://user-images.githubusercontent.com/2301026/100807447-9f446180-3432-11eb-963c-92298b584e11.png)

**Comment by antifree** [comment]
Hello,

You can specify `basePath` in dispatcher options. For example:
```
@page "/<my-base-path>/{**entity}"

.    .    .    .


@section Scripts {
    <script src="https://cdn.korzh.com/ed/1.1.1/easydata.min.js" type="text/javascript"></script>
    <script>
        window.addEventListener('load', function () {
            new easydata.crud.EasyDataViewDispatcher({
                   basePath: <my-base-path>
            }).run()
        });
    </script>
}
```

The default value is `easydata`.

**Comment by ilchenkob** [comment]
Thanks for such a quick reply!
Tried what you suggested and it works.
I guess that's worth mentioning in readme ;)

**Comment by Alerinos** [comment]
@ilchenkob @antifree add it to the documentation and readme

**Comment by malhoudmouad** [comment]
Hi ! 
This doesnt work on my side : 
easydata.min.js:2 Unable to find active entity for /mods/gestion
(anonymous) @ easydata.min.js:2
A @ easydata.min.js:2
k @ easydata.min.js:2
O @ easydata.min.js:2
g @ easydata.min.js:2
characterData
w @ easydata.min.js:2
a @ easydata.min.js:2
M @ easydata.min.js:2
I @ easydata.min.js:2
S @ easydata.min.js:2
(anonymous) @ easydata.min.js:2
o.a.f.onreadystatechange @ easydata.min.js:2
XMLHttpRequest.send
(anonymous) @ easydata.min.js:2
(anonymous) @ easydata.min.js:2
e @ easydata.min.js:2
e.send @ easydata.min.js:2
e.get @ easydata.min.js:2
t.loadMetaData @ easydata.min.js:2
t.run @ easydata.min.js:2
(anonymous) @ gestion:144

@page "/Mods/gestion/{**entity}"


<link rel="stylesheet" href="https://cdn.korzh.com/ed/1.4.8/easydata.min.css" />

<div id="EasyDataContainer"></div>

@section Scripts {
    <script src="~/js/easyData/easydata.min.js" type="text/javascript"></script>
    <script>
        window.addEventListener('load', function () {
            new easydata.crud.EasyDataViewDispatcher({
                basepath: '/Mods/gestion'
            }).run()
        });
    </script>
}
