### ISSUE TITLE
Export to Excel converts some date value to numbers

### ISSUE THREAD

**Issue by korzh** [KorzhCom/EasyData#52]
It does not happen for all values. I believe it occurs only for those ones where the month number is less than 13. Probably Excel confuses the month and day part in this case.

Here is an example of exported data. All values in the second column are dates.
![image](https://user-images.githubusercontent.com/966694/129756336-419ccc40-aa2b-4d13-b656-1abf3ab220c8.png)

The actual value in the 3d row is `12/02/2020`. In 4th - `03/06/2021`. So, I guess we can see the pattern.

**Comment by korzh** [comment]
Fixed in 1.3.3-rc01

**Comment by antifree** [comment]
Fixed in version 1.3.3. PR #55
