### ISSUE TITLE
Model Extension

### ISSUE THREAD

**Issue by SahilArora7** [KorzhCom/EasyData#53]
Hi Devs,

Can I extend the models and inject instead of using the default model.

Explanation:
For example the customer model has 10 properties, I want 5 from the existing model and add my own new properties into model.

Is that possible in EasyData.

thanks and regards.

**Comment by antifree** [comment]
Hi,

Yes, it is possible. You can hide properties that you do not want to show/edit etc using such an attribute:
```c#
  [MetaEntityAttr(Editable = false, ShowOnView = false, ShowInLookup = false)]
  public DateTime DateCreated { get; set;}
```

About adding other properties. Yes, you can do it using ModelTuner. For example:
```c#
 endpoints.MapEasyData(options => {
     options.Endpoint = "/api/super-easy-crud";
     options.UseDbContext<ApplicationDbContext>();

     options.UseModelTuner(model =>
      {
          var customerEntity = model.EntityRoot.FindSubEntity("Customer");
          var attr = model.CreateEntityAttr(new EasyData.MetaEntityAttrDescriptor() {
              Parent = customerEntity,
              Caption = "CustomProperty",
              DataType = EasyData.DataType.String,
              Kind = EasyData.EntityAttrKind.Virtual
          });
          customerEntity.Attributes.Add(attr);
      });
});
```

But if you add a property, that won't have representation in DbContext entity, it won't be processed, or even an error is possible. 
It would be better if you could describe the scenario you are trying to implement.

**Comment by SahilArora7** [comment]
The idea is simple, don't know if this product was designed to according to that.

I have my own models, but I am looking for tools that can do CRUD boiler plate code for me.

I reached at this code base and before committing I wanted to get things cleared. Probably if there is any documentation that is there so that I can look into it.

**Comment by korzh** [comment]
It depends on what you call a "model". In the current implementation of EasyData a "data model" equals to DbContext. In any case, it's all tied to the structure of the underlying database. 
EasyData architecture allows working with any database but it requires a special implementation of EasyDataManager class to support a particular DB. As for now, we have implementation only for Entity Framework Core.

So, if you describe what exactly you are trying to achieve, we will possibly be able to suggest a solution.

**Comment by egeozcan** [comment]
I was wondering if we could use proxy models (API-only) that have 2 way mappers. For example, Person vs APIPerson. It would work just 1-to-1 not to overcomplicate things. 

Perhaps the author wants the same thing but I'm not sure. I'd gladly create a more detailed issue if that's not the case and the maintainers would be interested.

**Comment by korzh** [comment]
Still not quite clear. "if we could use proxy models" - for what? 

If you think that EasyData has some kind of API representation for each model class, it's not correct. Instead, it has a Metadata object that contains information about all models (entities) and all attributes (properties) in those entities together with some other necessary information. This Metadata object is converted to its JSON representation and sent to the client on a "GetMetadata" request (usually the first one). 

So, if you have your own representation of your DB (not a DbContext), you will need to write a so-called "model loader" that fills the Metadata object by your DB representation.

**Comment by antifree** [comment]
I'll close due to inactivity
