### ISSUE TITLE
.NET 6 support 

### ISSUE THREAD

**Issue by antifree** [KorzhCom/EasyData#58]
There is a problem with .NET 6 version while loading DbContext metadata. Possibly there are other issues. 
Need investigation

**Comment by antifree** [comment]
I've added [branch](https://github.com/KorzhCom/EasyData/tree/net6.0-support) with fix. It seems that it is working now. The main question is if we need to force using EF Core 6 version with .NET 6.0 but not 5.0 or set minimum version 5.0 for both targets?

**Comment by korzh** [comment]
About EF Core, I guess we should try to leave it as EF Core 5.0 and just test both cases: 

1. With a .NET 6 app and EF Core 5 
2. With a .NET 6 app and EF Core 6

**Comment by antifree** [comment]
Related issue about new date & time types #61

**Comment by antifree** [comment]
I think we can close it
