### ISSUE TITLE
"Create" record does not show related entities

### ISSUE THREAD

**Issue by ilchenkob** [KorzhCom/EasyData#7]
**Steps to reproduce**

1. Launch EasyDataBasicDemo.NetCore31
2. Go to /easydata/OrderDetail
3. Click "Add Column" button (which should be called "Add Row" though)
4. Try to add Order or Product in "Create Order Detail" dialog window

**Actual Result**

"Navigation Values" buttons do not work.

![image](https://user-images.githubusercontent.com/2301026/101756440-4df13d80-3ad6-11eb-87b3-b15a7e16c9fa.png)

**Expected Result**

A dialog is shown which allows to choose Order or Product

**Comment by antifree** [comment]
Hello,
 it should be fixed in version 1.1.2. Please, update JS and .NET versions. Related issue #5
