### ISSUE TITLE
More correct default columns' widths

### ISSUE THREAD

**Issue by korzh** [KorzhCom/EasyData#72]
Currently (version 1.3), the default sizes for columns are wider than necessary in most cases.

For example, an Int32 "ID" column has 120px width while it really needs only a half of this size to show numbers up to billions.

The default size for date/time columns is 200px but for short dates 100px would be enough.

**Comment by antifree** [comment]
Let's add some callback function to grid options with such signature
```ts
columWidthResolver: (col: GridColumn) => number | undefined;
```

If no value is returned we will use the default for DataType, otherwise, we will use returned value

**Comment by korzh** [comment]
We have now semi-automatic columns' widths adjustment in EasyGrid. It's controlled by `EasyGridOptions.columnWidths` option when it's possible to set the default, minimum, and maximum width for each data type and also set `autoResize` option to one of the following values:
 * AutoResizeColumns.Never - no automatic columns' widths adjustment
 * AutoResizeColumns.Always - columns' widths will be adjusted for each page
 * AutoResizeColumns.Once (the default value) - columns' widths are adjusted automatically on the first page and then we use these values for all other pages without any corrections.
