### ISSUE TITLE
Minimal API sample

### ISSUE THREAD

**Issue by korzh** [KorzhCom/EasyData#78]
We need a "pure" .NET 6 sample project with minimal API Entity Framework 6 and all the latest C# 10 features we can use there.

**Comment by antifree** [comment]
It is already in playground. EasyDataAspNetCoreTest03

**Comment by korzh** [comment]
> It is already in playground. EasyDataAspNetCoreTest03

So, it means we just need to move it to Samples :)

**Comment by antifree** [comment]
And update README I think

**Comment by korzh** [comment]
Done. Now we have a [sample for .NET 6](https://github.com/KorzhCom/EasyData/tree/dev/samples/EasyDataBasicDemo.RazorPages.Net6) where all services and middlewares are defined in the Program.cs (the new approach).
