### ISSUE TITLE
Skip intermediate entities by default 

### ISSUE THREAD

**Issue by korzh** [KorzhCom/EasyData#79]
It's better to skip by default all intermediate entities (the ones that used to join other entities in many-to-many relationships). 

If there is a necessity to show some of them, it will still be possible to use either annotations `[MetaEntity(true)]` or the Fluent API for that.

**Comment by ErikEJ** [comment]
I EF Core 5 and later there may on be unnamed "Dictionary<string, object>" entities

**Comment by korzh** [comment]
> In EF Core 5 and later there may on be unnamed "Dictionary<string, object>" entities

Can you please give an example of a DbContext that generates such entities in the result?

**Comment by ErikEJ** [comment]
Please find a sample project attached
[EasyDataTest.zip](https://github.com/KorzhCom/EasyData/files/7735305/EasyDataTest.zip)

**Comment by korzh** [comment]
Fixed in 1.4.0-rc01

Now EasyData just skips the entities that are not listed as DbSets in the DbContext.
