### ISSUE TITLE
Integrate Claims Based data filtering

### ISSUE THREAD

**Issue by fasteddys** [KorzhCom/EasyData#82]
Hello, I am interested in this. But it seems outdated with the core versions, with the new version there are many new features, can you show a sample if this would work role based and claims based access. The current identity and new EF core allows ClientCascade to delete / update records with dependencies even if they have cyclic references.

**Comment by korzh** [comment]
We will investigate this. 
Could you please describe the scenario you would like to implement, so we could create a sample for exactly that (or a similar) scenario and understand what enhancements must be added to the library (if there are needed at all).

**Comment by fasteddys** [comment]
Hi Korzh,

As you are aware, businesses want to secure their data, for e.g. in our store many people log in to quickly check data and inventory.

The store owner and 3 store managers in different places are also logging in. only they should be allowed to see finance table , loan table data.

Because its regional for this small store, roles do not work. Claims allow you to add security to that data table, its more flexible. https://docs.microsoft.com/en-us/aspnet/core/security/authentication/claims?view=aspnetcore-6.0 

In my current/previous application, they have a page with a table to add new claims (nothing but text), then map those to groups or data, just like Active Directory.

Ours is only a store with vendors etc. But your solution will work with multitenants if you have claims.

Another nice [explanation ](https://stackoverflow.com/questions/21645323/what-is-the-claims-in-asp-net-identity)

**Comment by korzh** [comment]
Hello@fasteddys,

Can I ask, why did you close the issue? 

We are still going to implement the requested functionality in one of the upcoming releases.

**Comment by fasteddys** [comment]
Ohh that's great, I wasn't sure. There are samples on claims, let me share the current feature from another product the use.

Manage and apply claims:

Basically you need a MVC view to create new claims and assign them to the user.
Another  MVC view to create new claims and assign to role.
You can also setup the claims for the entity/VM so that only those have those claims.


  
[Help page 
](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-6.0)
setup Startup.cs
```
  
    services.AddAuthorization(options =>
    {
         // then what every you collected from korzh view to manage claims collect then
        options.AddPolicy("Claim_Name", x => x.RequireClaim("Claim_Name"));
    });
```

Then inside the UI   
```
    if ((AuthorizationService.AuthorizeAsync(User, "Claim_Name")).Result.Succeeded){
        //show Korzh ui Grid element
    }
```

When you need to get your claim user this helper

```
public static string GetKorzhSpecificClaim(this ClaimsIdentity claimsIdentity, string claimType)
{
    var claim = claimsIdentity.Claims.FirstOrDefault(x => x.Type == claimType);

    return (claim != null) ? claim.Value : string.Empty;
}
```

To claim on user

`@((ClaimsIdentity) User.Identity).GetSpecificClaim("someclaimtype")`

**Comment by Zubi-Alinta** [comment]
> Hello@fasteddys,
> 
> Can I ask, why did you close the issue?
> 
> We are still going to implement the requested functionality in one of the upcoming releases.

Hi Korzh, 

First, thank you for this amazing app. I was wondering if the claim-based solution is released yet. I was looking for options to implement token-based authentication in the react sample project.

Thank you,
Zubi
