### ISSUE TITLE
Convert all samples to .NET 6

### ISSUE THREAD

**Issue by korzh** [KorzhCom/EasyData#83]
We can leave one of the samples (EasyDataBasicDemo.RazorPages most likely) on .NET 5 just to make sure everything works well after the latest updates.

**Comment by Alerinos** [comment]
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-7-preview-1/#inject-services-into-custom-validation-attributes-in-blazor
The first version 7 has already appeared, it is worth adapting to the new standards.

**Comment by antifree** [comment]
We will make a sample with .NET 7 when it will be released.

**Comment by antifree** [comment]
Added .NET 6 samples to dev
