### ISSUE TITLE
Issues with Microsoft.AspNetCore.Identity.EntityFrameworkCore

### ISSUE THREAD

**Issue by sanket-pattekar** [KorzhCom/EasyData#87]
Hi

I am using Microsoft.AspNetCore.Identity.EntityFrameworkCore for Identity. I have also defined ApplicationRole and ApplicationUser models in my code as follows

public class ApplicationRole : IdentityRole{}
public class ApplicationUser : IdentityUser{}

The problem is that in the method DbContextMetaDataLoader.GetDbContextTypes(). This method throws as exception "An item with the same key has already been added."

When debugged, I see that there are 2 enteries for ApplicationRole and ApplicationUser and the call to .ToDictionary(tt => tt.Item1, tt => tt.Item2); is throwing the exception

Can you please fix the same. My Asp,net version is 5.0

Sanket

**Comment by korzh** [comment]
Hello,

1. What version of EasyData do you use? 

2. Could you please attach (or share somewhere) your DbContext class with all model classes? We will try to reproduce the problem.

**Comment by sanket-pattekar** [comment]
Hi

1. Using the latest version of EasyData. First I used it with nuget and then I cloned the master branch.
2. Sharing a snippet of the requested classes

public class ApplicationDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, string>
{
	public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
		: base(options)
	{
	}
	
	protected override void OnModelCreating(ModelBuilder builder)
	{
		base.OnModelCreating(builder);
	}

	public DbSet<ApplicationUser> ApplicationUser { get; set; }
	public DbSet<ApplicationRole> ApplicationRole { get; set; }

	public DbSet<CustomerMaster> CustomerMaster { get; set; }
}

public class ApplicationRole : IdentityRole
{
	public string Description { get; set; }
}
	
public class ApplicationUser : IdentityUser
{
	public string FullName { get; set; }

	[Timestamp]
	public byte[] RowVersion { get; set; }
}

To get it working, I changed the GetDbContextTypes to following
private IDictionary<Type, int> GetDbContextTypes()
        {
            var collection = DbContext.GetType()
                    .GetProperties()
                    .Where(p => p.PropertyType.IsGenericType
                        && typeof(DbSet<>).IsAssignableFrom(p.PropertyType.GetGenericTypeDefinition()))
                    .Select((p, index) => (p.PropertyType.GetGenericArguments()[0], index));

            Dictionary<Type, int> dbContextTypes = new Dictionary<Type, int>();
            foreach (var item in collection)
            {
                Type itemType = item.Item1;
                int itemIndex = item.index;

                if(dbContextTypes.ContainsKey(itemType))
                {
                    continue;
                }
                else
                {
                    dbContextTypes.Add(itemType, itemIndex);
                }
            }

            return dbContextTypes;

            //return DbContext.GetType()
            //        .GetProperties()
            //        .Where(p => p.PropertyType.IsGenericType
            //            && typeof(DbSet<>).IsAssignableFrom(p.PropertyType.GetGenericTypeDefinition()))
            //        .Select((p, index) => (p.PropertyType.GetGenericArguments()[0], index))
            //        .ToDictionary(tt => tt.Item1, tt => tt.Item2);
        }

**Comment by korzh** [comment]
Hm. Got it. We will add the necessary fix to the next update.

It's actually interesting how EF Core itself resolves this configuration since `IdentityDbContext` already has `DbSet<ApplicationUser>` property (as `Users`) and  `DbSet<ApplicationRole>` property (as `Roles`) defined inside it.

**Comment by sanket-pattekar** [comment]
Checked in version 1.4.1. This is working fine as expected
