### ISSUE TITLE
Changing the default endpoint not working

### ISSUE THREAD

**Issue by sanket-pattekar** [KorzhCom/EasyData#89]
Hi

I followed the steps to change the endpoint from easydata to masterdata. However this is not working. Can you please check the steps

1. Added  options.Endpoint = "/api/masterdata"; in startup
2. Added the route [Route("masterdata")] in controller
3. In the javascript section used endpoint: '/api/masterdata'

Getting a blank page when I access it with /masterdata. Can you please check and revert

Sanket

**Comment by korzh** [comment]
Could you please attach your project where this problem is reproducible?

Did you check the Network tab in Developer Tools in your browser when you were opening that page? What requests and the results of those requests did you see there?

**Comment by sanket-pattekar** [comment]
Hi

I cannot upload anything due to internal security. The url that I see in the network tab is the new one /masterdata. 

Also I tried to create a new project and added few things, The page works w/masterdatahen the pattern is /easydata. However when I change to /masterdata then that shows a blank page.

Sanket

**Comment by korzh** [comment]
It's not necessary to share your own project. We just need any project where the error is reproducible. 

You can take one of our samples, make the necessary modifications and share it on OneDrive, Google Drive, or whenever you want.

**Comment by korzh** [comment]
It seems I've missed the fact you moved not only the API endpoint but the page itself (which wouldn't have missed if there was a proper testing project :)).

Anyway, when you change the default address for the main CRUD page (which is `/easydata`) you need to specify the base path in the dispatcher's options:

```
    new EasyDataViewDispatcher({
        basePath: '/masterdata',
        endpoint: '/api/masterdata'
    }).run()

**Comment by sanket-pattekar** [comment]
Thanks It is working now. 

Being a developer, I do understand the importance of testing project. However there are restrictions on what you can post in the company environment. Anyways thanks for all your prompt responses.

Sanket
