### ISSUE TITLE
System.NullReferenceException: „Object reference not set to an instance of an object.”

### ISSUE THREAD

**Issue by Alerinos** [KorzhCom/EasyData#91]
Error:
```
System.NullReferenceException: „Object reference not set to an instance of an object.”
```
![image](https://user-images.githubusercontent.com/42449535/148809730-2fd2e340-fd48-47bb-9354-113f32fe67f2.png)

Models;
```cs
namespace Lib.Culture.Models
{
    public class Country 
    {
        public int Id { get; set; }
        public string Name { get; set; }                    // Nazwa kraju Wielka Brytania
        public Language Language { get; set; }              // Język jaki jest używany
        public string ShortName { get; set; }               // Krótka nazwa kraju, np uk
        public string Currency { get; set; }                // Waluta, np USD, PLN etc
        public string CurrencySymbol { get; set; }          // Symbol, np $, zł 
        public string DateFormat { get; set; } = "DD-MM-YYYY";  // Format daty, DD-MM-YYYY
        public bool LeftToRight { get; set; } = true;       // Tekst od lewej do prawej (Arabia ma np od prawej do lewej)
    }
}

namespace Lib.Culture.Models
{
    public class Language
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
    }
}
```
Console log:
```
[18:19:09 INF] Executing endpoint '/EasyData'
[18:19:09 INF] Route matched with {page = "/EasyData", action = "", controller = ""}. Executing page /EasyData
[18:19:09 INF] Executing handler method Crud.Pages.EasyDataModel.OnGet - ModelState is Valid
[18:19:09 INF] Executed handler method OnGet, returned result .
[18:19:09 INF] Executing an implicit handler method - ModelState is Valid
[18:19:09 INF] Executed an implicit handler method, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
[18:19:09 INF] Executed page /EasyData in 35.0154ms
[18:19:09 INF] Executed endpoint '/EasyData'
[18:19:09 INF] Request finished HTTP/1.1 GET http://localhost:5021/easydata - - - 200 - text/html;+charset=utf-8 94.8274ms
[18:19:09 INF] Request starting HTTP/1.1 GET http://localhost:5021/api/easydata/models/__default application/json -
[18:19:09 INF] Executing endpoint 'EasyData API'
[18:19:09 INF] Entity Framework Core 6.0.1 initialized 'CultureContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:6.0.1' with options: None
[18:19:09 INF] Executed endpoint 'EasyData API'
[18:19:09 INF] Request finished HTTP/1.1 GET http://localhost:5021/api/easydata/models/__default application/json - - 200 - application/json;+charset=utf-8 111.8068ms
[18:19:11 INF] Request starting HTTP/1.1 POST http://localhost:5021/api/easydata/models/__default/sources/Country/fetch application/json 42
[18:19:11 INF] Executing endpoint 'EasyData API'
[18:19:11 INF] Entity Framework Core 6.0.1 initialized 'CultureContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:6.0.1' with options: None
[18:19:11 INF] Executed DbCommand (9ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT COUNT_BIG(*)
FROM [Culture_Country] AS [c]
[18:19:11 WRN] The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results. If the 'Distinct' operator is used after 'OrderBy', then make sure to use the 'OrderBy' operator after 'Distinct' as the ordering would otherwise get erased.
[18:19:11 WRN] The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results. If the 'Distinct' operator is used after 'OrderBy', then make sure to use the 'OrderBy' operator after 'Distinct' as the ordering would otherwise get erased.
[18:19:11 INF] Executed DbCommand (2ms) [Parameters=[@__p_0='?' (DbType = Int32), @__p_1='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT [c].[Id], [c].[Currency], [c].[CurrencySymbol], [c].[DateFormat], [c].[LanguageId], [c].[LeftToRight], [c].[Name], [c].[ShortName]
FROM [Culture_Country] AS [c]
ORDER BY (SELECT 1)
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
```

What did I do wrong?
I am using ef core and .net 6
I find it works fine when there is no relationship

**Comment by antifree** [comment]
Hello, 

Currently, EasyData does not `Include` related entities on the query to the database. So possibly your code accesses Country. Language of an item where there is no Language (you can also see from logs that there is no JOIN in a SQL). 

We will investigate how to make it possible to include related entities

**Comment by korzh** [comment]
Hello,

1. First of all, it would be great to see the full stack trace of this exception.
2. Secondly, you didn't mention what exactly you did when the error occurred. Did you just open the Country dataset? Or maybe the dataset was opened without any problem and the error occurred when you filtered it? Please describe the whole setup more in detail.

**Comment by Alerinos** [comment]
@korzh  sorry, after recreating the subpage. It doesn't even display anything.
```cs
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=EasyData.EntityFrameworkCore.Relational
  Ślad stosu:
   w EasyData.Services.EasyDataManagerEF`1.<>c__DisplayClass4_1.<FetchDatasetAsync>b__4(MetaEntityAttr attr)
```
![image](https://user-images.githubusercontent.com/42449535/148823753-75a94c9c-0dff-49a9-a24f-6d2276ab15e1.png)

![image](https://user-images.githubusercontent.com/42449535/148823912-43398698-845d-4880-b6fa-4830fb69ca4e.png)

**Comment by korzh** [comment]
Сould you please also share the whole DbContext and all customization you (probably) make there in `OnModelCreating`  method.

Or at least all the definitions for the `Country` and `Language` DbSets

**Comment by Alerinos** [comment]
[Culture.zip](https://github.com/KorzhCom/EasyData/files/7841627/Culture.zip)
I am sending the entire library, it is small and simple so there will be no problems.
```
Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```
Base MSSQL 

Startup:
```cs
        services.AddDbContext<Culture.CultureContext>(options =>
            options.UseSqlServer(dataBase.Main));
```

**Comment by Alerinos** [comment]
Found a bug? I can help? Any recommendations what should I do?

**Comment by korzh** [comment]
Hello,

Couldn't reproduce bug on an empty dataset. So, the problem must be in the data. Could you please publish a backup of your data, at least for Country and Language tables? A few records will be enough. 

To create a data backup you can use our [dbtool utility](https://github.com/KorzhCom/Korzh.DbUtils). It's easy to setup and then to export DB data to JSON or XML formats. And it's easy to modify the exported data after that since you get just text files.

**Comment by Alerinos** [comment]
@korzh 
Use ``Initialize`` in ``CultureContext``


```cs
    public static void Initialize(CultureContext _context)
    {
        _context.Database.EnsureCreated();


        var language = new List<Models.Language> {
            new Models.Language
            {
                Name = "English",
                ShortName = "en",
            },
            new Models.Language
            {
                Name = "Polish",
                ShortName = "pl",
            }
        };
        if(_context.Language.Any() == false)
        {
            _context.AddRange(language);
            _context.SaveChanges();
        }



        var country = new List<Models.Country> {
            new Models.Country {
                Name = "United Kingdom",
                ShortName = "uk",
                Language = _context.Language.Single(x => x.Name == "English"),
                Currency = "gbp",
                CurrencySymbol = "£",
                DateFormat = "DD-MM-YYYY",
            },
            new Models.Country {
                Name = "United States of America",
                ShortName = "usa",
                Language = _context.Language.Single(x => x.Name == "English"),
                Currency = "usd",
                CurrencySymbol = "$",
                DateFormat = "YYYY-MM-DD",
            },
            new Models.Country {
                Name = "Polish",
                ShortName = "pl",
                Language = _context.Language.Single(x => x.Name == "Polish"),
                Currency = "pln",
                CurrencySymbol = "zł",
                DateFormat = "DD-MM-YYYY",
            },
        };
        if (_context.Country.Any() == false)
        {
            _context.AddRange(country);
            _context.SaveChanges();
        }



        var variables = new List<Models.Variables>
        {
            new Models.Variables
            {
                Name = "Hello {0}",
                Description = "The value {0} replaces the username"
            }
        };
        if (_context.Variables.Any() == false)
        {
            _context.AddRange(variables);
            _context.SaveChanges();
        }

    }
```

**Comment by korzh** [comment]
Hello,

We've published version 1.4.1-rc01 (both for EasyData .NET packages and EasyData JS scripts). 
This update fixes the issue.

**Comment by Alerinos** [comment]
Hello,
It works, when I add / edit I get this error in javascript.
You are doing a great job. A very useful tool.


```
easydata.min.js:2 
        
       Uncaught TypeError: Cannot read properties of null (reading 'id')
    at t.setupLookupField (easydata.min.js:2:148951)
    at t.addFormField (easydata.min.js:2:155216)
    at t.build (easydata.min.js:2:156267)
    at t.showEditForm (easydata.min.js:2:165933)
    at t.rowDbClickHandler (easydata.min.js:2:166377)
    at Object.callback (easydata.min.js:2:124221)
    at s (easydata.min.js:2:15809)
    at t.fire (easydata.min.js:2:15843)
    at e.fireEvent (easydata.min.js:2:108906)
    at HTMLDivElement.<anonymous> (easydata.min.js:2:120217)
```

**Comment by korzh** [comment]
Hello,

Does it occur for the same Country entity we discussed before? Could you please share screenshots of how your "view" page and your "edit" dialog look like?

**Comment by Alerinos** [comment]
https://gyazo.com/27373fe80859627ad67c7ed02d49d5f5
The problem occurs wherever there is a relationship.
Above a short video.

**Comment by korzh** [comment]
Hello,

We've published version 1.4.1-rc02. 

The real problem was in shadow properties in model classes, those ones in particular that are created automatically for navigation properties.

For example, when we define the following model class:
```
public class Culture {
    public Language Lanaguage { get; set; }
    .     .     .     .     .
}
```
Entity Framework creates a shadow property `LanguageId` automatically for the Culture entity. 

Unfortunately, with the current implementation of the Fetch procedure, we can't get the values for shadow properties, so we just hide them and corresponding navigation properties. This fix is available in 1.4.1-rc02.

If you need to give your users a possibility to define such connections (like Language in our example) you will need to add the corresponding foreign key property explicitly:

```
public class Culture {
    public Language Lanaguage { get; set; }

    public int? LanguageId {get; set; }  //here we use the type of the primary key of the Language entity
    .     .     .     .     .
}
```

**Comment by Alerinos** [comment]
Great, they work!

It can be done that if it detects a foreign key it automatically appends the Id to the end just like EF core does. In this case, you do not need to define two values in the model. It seems to be possible to do.

**Comment by Alerinos** [comment]
![image](https://user-images.githubusercontent.com/42449535/149644839-cdaaef09-ef90-4e30-9a5f-fbf3bc20ddcd.png)

Last problem, leave the ID field (if you want to put your own) but do not required. The ID is always auto increment, so if you do nothing it will either do +1 or generate a GUID

**Comment by Alerinos** [comment]
Another cool idea is you can insert default values that are in the model. So if we have:
```cs
public string DateFormat { get; set; } = "DD-MM-YYYY";
```
We will get this result:
![image](https://user-images.githubusercontent.com/42449535/149644933-57605c6c-1222-4394-90c1-88c837336ad5.png)

**Comment by Alerinos** [comment]
I have such an error when adding any value.
![image](https://user-images.githubusercontent.com/42449535/149645687-3bc9e708-5a85-401d-9e80-86f57eea3cd0.png)

![image](https://user-images.githubusercontent.com/42449535/149645709-3f882e95-1422-4abd-b0d5-c05ccf5b22e5.png)
![image](https://user-images.githubusercontent.com/42449535/149645720-17c83740-fb88-49bb-8f15-594764faed2b.png)

**Comment by korzh** [comment]
> Great, they work!
> 
> It can be done that if it detects a foreign key it automatically appends the Id to the end just like EF core does. In this case, you do not need to define two values in the model. It seems to be possible to do.

No, it will not work this way. Actually, it was the cause of the problem in the first place. EF automatically added those "shadow" properties (like LanguageId) but our "fetch" code can't get a value for such properties (because they don't really exist in the model class). That's why we had to remove them (and the corresponding navigation properties) to avoid the exception. 
There can be other solutions: to modify our fetch procedure to make it work directly through SQL and IDataReader or to create a custom type and ask EF to map into that new type instead of the original model class. However, both these options require much more time. We already have an issue (#95 ) about that and it will be implemented in future updates.

**Comment by korzh** [comment]
> ![image](https://user-images.githubusercontent.com/42449535/149644839-cdaaef09-ef90-4e30-9a5f-fbf3bc20ddcd.png)
> 
> Last problem, leave the ID field (if you want to put your own) but do not required. The ID is always auto increment, so if you do nothing it will either do +1 or generate a GUID

We have already fixed that. Please update your JS script to 1.4.1 (https://cdn.korzh.com/ed/1.4.1/easydata.min.js). If you use it already, it's probably a cache problem. The previous version of the script was cached in your browser and so, you didn't use the latest update.

**Comment by korzh** [comment]
> Another cool idea is you can insert default values that are in the model. 

Let's create another issue about that. We need to close this one first and then move forward with new features.

**Comment by korzh** [comment]
@Alerinos Have you checked that problem with ID fields you mentioned before and that we believe is already fixed in the latest easydata.js script?

**Comment by Alerinos** [comment]
@korzh 
Yes, everything works. There is one problem with another model that I haven't uploaded before, but I will test more and create a new topic.
Great job and support!
