### ISSUE TITLE
System.TypeInitializationException exception when we run Excel exporter on Linux 

### ISSUE THREAD

**Issue by korzh** [KorzhCom/EasyData#93]
This problem is caused by `System.Drawing.Common` package used in the ClosedXml.  The library creators are [aware of this problem](https://github.com/ClosedXML/ClosedXML/issues/1694) already but the fix is not available yet.

I see two possible solutions to this (besides just waiting for a new release of ClosedXml):

1. It seems that `System.Drawing.Common` is actually used only in one method `AdjustToContents`. We can write our own method that will have different behavior on different platforms. On Windows that new method will just call `AdjustToContents`. On other platforms, it will try to calculate the width (or to do whatever that `AdjustToContents` does) "manually" or will just do nothing.

2. We can create our own branch of ClosedXml library that fixes that problem according to the [instructions provided by MS](https://github.com/dotnet/designs/blob/a15a8c7a324c482c5e38b73e46c2afe56f6bd504/accepted/2021/system-drawing-win-only/system-drawing-win-only.md) and simply include the whole library into our EasyData.Exporters.ClosedXml
Moreover, there are some [PRs already](https://github.com/ClosedXML/ClosedXML/pull/1696) in ClosedXml repository that might address this issue. So, it's possible that we will not need to create that new branch from scratch.

**Comment by antifree** [comment]
I think it is not good to include the whole library in our ClosedXml. It is better to wait for the fix, or downgrade the referenced version:
> No, System.Drawing.Common is a standalone package that does not ship as part of the shared framework. For that reason if an application wants to keep using System.Drawing.Common on Unix and move to .NET 6, they can reference the 5.0.x version of the package.

**Comment by korzh** [comment]
The main problem (with the exception) has been fixed in 1.4.1. For the rest, a new issue (#106) was created.
