### ISSUE TITLE
ID problem, NameID is not shown when adding

### ISSUE THREAD

**Issue by Alerinos** [KorzhCom/EasyData#94]
Model:
```cs
public class Details
{
    public int Id { get; set; }
    public Guid GameId { get; set; }
    public string ShortDescription { get; set; } = string.Empty;                    // Krótki opis np do google, fejsa itp
    public string Description { get; set; } = string.Empty;                         // Opis gry
    public string Background { get; set; } = string.Empty;                          // Tło gry, jeżeli puste to nie ma tła
    public string Logo { get; set; } = string.Empty;                                // Logo gry
    public bool Nsfw { get; set; } = false;                                         // Dla dorosłych
    public int AverageGameTime { get; set; } = 0;                                   // Średni czas gry w godzinach
    public DateTime DateReleased { get; set; } = DateTime.MinValue;                 // Data publikacji
    public DateTime DateLastEdit { get; set; } = DateTime.Now;                      // Ostatnia edycja 
    public DateTime DateCreate { get; set; } = DateTime.Now;                        // Data dodania
}
```

Panel:
![image](https://user-images.githubusercontent.com/42449535/149447413-b71e532c-97ca-4234-b08e-e53009eb6523.png)
As you can see above, there is no ``GameId`` column

I noticed this error when I wanted to enter GUID in the ID, but it turned out to be int and it won't work.

If I change GUID to relation, unfortunately there is a blank page.

Suggestion: you can add a tag to the model so that the textarea appears instead of input

**Comment by korzh** [comment]
Hello,

Can't reproduce this in the newest version (1.4.1-rc01). We have a Guid field in a model class and it has the corresponding text box in the Create or Edit dialog.

As for Id field. If it's auto-generated, then it's better to mark it as "Editable = false", so it will not be shown in the Create/Edit dialogs (and so, the UI will not require to enter its value).  In the feature versions we will try to turn "editable" off for such fields automatically. There is an issue about that (#96 ) already.

**Comment by Alerinos** [comment]
Now it works, a nice option would be if when adding / editing it would not sort alphabetically but as it is in the model. Often, important things are placed at the top and less at the bottom. Example:
```cs
    public int Id { get; set; }
    public Guid GameId { get; set; }
```
![image](https://user-images.githubusercontent.com/42449535/149605954-2a72242a-2cf9-4c4e-a8d9-a84a550c2828.png)

**Comment by Alerinos** [comment]
Is it possible to convert input to textarea?
For example, Description is a long text so it will be easier in a textarea.
Example:
```cs
[MetaEntity(Type = "textarea")]
public string Description { get; set; } = string.Empty;  
```

**Comment by antifree** [comment]
Hello,
Yes, it is possible. You can do it in such a way:
```c#
   endpoints.MapEasyData((options) => {
      .     .    .   .     .    . 
      options.UseModelTuner(model =>
      {
          var detailsDesc = model.FindEntityAttr("Details.Description");
          detailsDesc .DefaultEditor = new TextValueEditor($"TVE_MULTI_{categoryDesc.Id}")
          {
              Multiline = true
          };
   });
```

We will consider, how to make it easier to configure it

**Comment by korzh** [comment]
I guess adding something like `Multiline = true` for `MetaEntityAttr` annotation would be more convenient.

**Comment by Alerinos** [comment]
He also proposes adding support for this:
```
https://docs.microsoft.com/pl-pl/dotnet/api/system.componentmodel.dataannotations?view=net-6.0
```
Asp.net itself has input verification. You use this when creating models, and even when creating a migration, it creates column values in the database.

**Comment by antifree** [comment]
It better to create a separate issue for validators
