### ISSUE TITLE
Support for browser back function.

### ISSUE THREAD

**Issue by Alerinos** [KorzhCom/EasyData#98]
When editing / adding data, I often click back on the mouse, unfortunately it returns to the previous page. You can add javascript support to capture back and make an event like "Back to entities"

https://gyazo.com/9db16abc165d3b4c1607d9281d75220c

Event:
```js
window.onhashchange = function() {
 //Back to entities
}
```

**Comment by antifree** [comment]
Resolved in 0ca13cebfea848e619bcc512e6f3f1574451be4c
